language: c

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq apt-transport-https python-docutils libgeoip1 libgeoip-dev
  - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish41/script.deb.sh | sudo bash
  - sudo apt-get -q update
  - sudo apt-get install varnish
  - sudo apt-get install varnish-dev

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make

script:
  - make check -j4 VERBOSE=1

compiler:
  - clang
  - gcc
